EXEC msdb.dbo.sp_delete_database_backuphistory @database_name = N'AirStats'
GO
USE [master]
GO
ALTER DATABASE [AirStats] SET  SINGLE_USER WITH ROLLBACK IMMEDIATE
GO

GO
USE [master]
GO
/****** Object:  Database [AirStats]    Script Date: 6/1/2016 8:59:39 PM ******/
DROP DATABASE [AirStats]
GO


/****** Object:  Database [AirStats]    Script Date: 6/1/2016 8:08:32 PM ******/
CREATE DATABASE [AirStats]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AirStats_Primary', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQL2016\MSSQL\DATA\AirStats_Primary.mdf' , SIZE = 65536KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB ), 
 FILEGROUP [DATA01]  DEFAULT
( NAME = N'AirStats_Data_01', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQL2016\MSSQL\DATA\AirStats_Data_01.ndf' , SIZE = 8388608KB , MAXSIZE = 50176000KB , FILEGROWTH = 1048576KB )
 LOG ON 
( NAME = N'AirStats_log',		FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQL2016\MSSQL\DATA\AirStats_log.ldf' ,	SIZE = 2097152KB , MAXSIZE = 12582912KB , FILEGROWTH = 1048576KB )
GO

ALTER DATABASE [AirStats] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AirStats].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AirStats] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AirStats] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AirStats] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AirStats] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AirStats] SET ARITHABORT OFF 
GO

ALTER DATABASE [AirStats] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AirStats] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AirStats] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AirStats] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AirStats] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AirStats] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AirStats] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AirStats] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AirStats] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AirStats] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AirStats] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AirStats] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AirStats] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AirStats] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AirStats] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AirStats] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AirStats] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AirStats] SET RECOVERY FULL 
GO

ALTER DATABASE [AirStats] SET  MULTI_USER 
GO

ALTER DATABASE [AirStats] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AirStats] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AirStats] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AirStats] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AirStats] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AirStats] SET QUERY_STORE = OFF
GO

USE [AirStats]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [AirStats] SET  READ_WRITE 
GO


